services:
  - type: web
    name: taskflow
    runtime: node
    plan: free
    rootDir: .
    buildCommand: |
      cd frontend
      npm install
      npm run build
      cd ../backend
      npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false